services:
  - type: web
    name: smart-agri-dss-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GEMINI_API_KEY
        sync: false
      - key: CDSE_CLIENT_ID
        sync: false
      - key: CDSE_CLIENT_SECRET
        sync: false
